[req]
default_bits       = 2048
distinguished_name = req_distinguished_name
req_extensions     = req_ext
x509_extensions    = req_ext
prompt             = no

[req_distinguished_name]
C  = IN
ST = KA
L  = Bangalore
O  = Dev
CN = *.local   # wild card cert for demo purpose

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1 = *.local
DNS.2 = local
