version: 2.1

executors:
  go-toolchain:
    docker:
      - image: golang:1.24.11-alpine3.23
    environment:
      GOCACHE: /tmp/go-cache

jobs:
  test:
    executor: go-toolchain
    steps:
      - checkout
      - run: |
          cd go-application && go test ./...