apiVersion: gateway.nginx.org/v1alpha1
kind: RateLimitPolicy
metadata:
  name: demo-rate-limit
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: demo-route
  ratelimit:
    requestsPerUnit: 5
    unit: Second 
