apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "6313c99e-2b01-40b1-b547-9755dc43cf34"
    keyvaultName: "anuroop-kv"
    tenantID: "3241b922-8d4a-4339-9b21-5009e9c776b8"
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret

