apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base   # checkout the manifests from that specific dir

images:
  - name: anuroop21/go-app
    newTag: 2690838a1deff553ae9735524da41b8caa3b1fa5
