apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base   # checkout the manifests from that specific dir

images:
  - name: anuroop21/go-app
    newTag: 03699672f7eea97cf472a3f0ceba9385d3819323
