apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base   # checkout the manifests from that specific dir

images:
  - name: anuroop21/go-app
    newTag: 44a0608de6d247dab4b44b0958b4a9c3997ad711
